name = "Tandwiel"
author = "spectrapulse"
version = "0.1.0a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8b774e4fc3847f5c6bdc9da766a40b80a498809ce5454ae49d55a6fd76691e9"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
datapack-folder = "config/paxi/datapacks"
