name = "Tandwiel"
author = "spectrapulse"
version = "0.1.0a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9fa687272e2704cce0c103bd1573dbd17cefbe170a3863b453d642790e57482"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
datapack-folder = "config/paxi/datapacks"
