name = "Tandwiel"
author = "spectrapulse"
version = "0.1.0a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00475dcb77d8716941f0f0ed702615e2918ee61cc006565d743f98c1a6ef6873"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
datapack-folder = "config/paxi/datapacks"
