name = "Tandwiel"
author = "spectrapulse"
version = "0.1.0a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a83ce17ab4b4d82fedb9149a5bc6e0adfd121fde49d4fa42720f4c7bea7d99d"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
datapack-folder = "config/paxi/datapacks"
