name = "Tandwiel"
author = "spectrapulse"
version = "0.1.0a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b590cb055ecc2c5fb3bbf22da6324d2b46e12a5dd5746194f077d3f04b721a13"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
datapack-folder = "config/paxi/datapacks"
